### ISSUE TITLE
NameError: name 'check_for_args' is not defined

### ISSUE THREAD

**Issue by microidz** [DanMcInerney/msf-autoshell#4]
Hi,

I just Git cloned the latest commit on 2 different systems and I'm getting the following error on both systems:

--

msf > python msf-autoshell.py -n /root/victim/nessus/victim_10_0_1_0.nessus
[*] exec: python msf-autoshell.py -n /root/victim/nessus/victim_10_0_1_0.nessus

Traceback (most recent call last):
  File "msf-autoshell.py", line 460, in <module>
    check_for_args()
NameError: name 'check_for_args' is not defined
msf >

**Comment by DanMcInerney** [comment]
Oops, I introduced this bug via a recent minor edit. Fixed now. That function was removed but the reference to it was not.

**Comment by microidz** [comment]
All better now.

Thx!

- M
